/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  EmployeeBenefits as PrismaEmployeeBenefits,
} from "@prisma/client";

export class EmployeeBenefitsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EmployeeBenefitsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.employeeBenefits.count(args);
  }

  async employeeBenefitsItems<T extends Prisma.EmployeeBenefitsFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeBenefitsFindManyArgs>
  ): Promise<PrismaEmployeeBenefits[]> {
    return this.prisma.employeeBenefits.findMany<Prisma.EmployeeBenefitsFindManyArgs>(
      args
    );
  }
  async employeeBenefits<T extends Prisma.EmployeeBenefitsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeBenefitsFindUniqueArgs>
  ): Promise<PrismaEmployeeBenefits | null> {
    return this.prisma.employeeBenefits.findUnique(args);
  }
  async createEmployeeBenefits<T extends Prisma.EmployeeBenefitsCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeBenefitsCreateArgs>
  ): Promise<PrismaEmployeeBenefits> {
    return this.prisma.employeeBenefits.create<T>(args);
  }
  async updateEmployeeBenefits<T extends Prisma.EmployeeBenefitsUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeBenefitsUpdateArgs>
  ): Promise<PrismaEmployeeBenefits> {
    return this.prisma.employeeBenefits.update<T>(args);
  }
  async deleteEmployeeBenefits<T extends Prisma.EmployeeBenefitsDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeBenefitsDeleteArgs>
  ): Promise<PrismaEmployeeBenefits> {
    return this.prisma.employeeBenefits.delete(args);
  }
}
